config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    get '/customers' => 'customers#index', as: 'customers'
    get '/customers/:id' => 'customers#show', as: 'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/:id' => 'customers#update', as: 'update'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :order_details
  end

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'edit_customer'
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/deleteprocess' => 'customers#deleteprocess', as: 'deleteprocess'
    patch '/customers/information' => 'customers#update', as: 'customer'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post '/orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get '/orders/completion' => 'orders#completion', as: 'completion'
    resources :orders
    resources :items
    resources :cart_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (non_taxed_price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :item_name, :introduction, :non_taxed_price)
  end
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="row">
    <h4>
      <strong>商品編集</strong>
    </h4>
  </div>

<%= form_with model: @item, url: admin_item_path do |f| %>

  <table class="col-5">
    <tbody>
      <tr>
        <td class="col-3">商品画像</td>
        <td class="col-3"><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <td class="col-3">商品名</td>
        <td class="col-3"><%= f.text_field :item_name, style: "width:100%" %></td>
      </tr>
      <tr>
        <td class="col-3">商品説明</td>
        <td class="col-3"><%= f.text_area :introduction, style: "width:100%", rows: "5" %></td>
      </tr>
      <tr>
        <td class="col-3">税抜き価格</td>
        <td class="col-3"><%= f.text_field :non_taxed_price, style: "width:100%" %></td>
      </tr>
      <tr>
        <td class="col-3"></td>
        <td class="col-3"><%= f.submit "変更を保存", class:"btn btn-success" %></td>
      </tr>
    </tbody>
  </table>
<% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="row">
    <h4>
      <strong>商品一覧</strong>
    </h4>
    <div class="col">
      <%= link_to '商品新規登録', new_admin_item_path, class:"btn btn-outline-dark mr-3" %>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="col-1">商品ID</th>
        <th class="col-3">商品名</th>
        <th class="col-3">税抜き価格</th>
      </tr>
    </thead>
    <tbody>
    <% @items.each do |item| %>
      <tr>
        <th class="row"><%= item.id %></th>
        <td><%= link_to item.item_name, admin_item_path(item.id) %></td>
        <td><%= item.non_taxed_price %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
    <%= paginate @items %>
</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h4>
        <strong>商品新規登録</strong>
      </h4>
    </div>
  </div>
  <%= form_with model: @item, url: admin_items_path do |f| %>

  <table class="col-5">
    <tbody>
      <tr>
        <td class="col-3">商品画像</td>
        <td class="col-3"><%= f.file_field :image, accept: "image/*" %></td>
      </tr>
      <tr>
        <td class="col-3">商品名</td>
        <td class="col-3"><%= f.text_field :item_name, style: "width:100%" %></td>
      </tr>
      <tr>
        <td class="col-3">商品説明</td>
        <td class="col-3"><%= f.text_area :introduction, style: "width:100%", rows: "5" %></td>
      </tr>
      <tr>
        <td class="col-3">税抜き価格</td>
        <td class="col-3"><%= f.text_field :non_taxed_price, style: "width:100%" %></td>
      </tr>
      <tr>
        <td class="col-3"></td>
        <td class="col-3"><%= f.submit "新規登録", class:"btn btn-success" %></td>
      </tr>
    </tbody>
  </table>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h4>
        <strong>商品詳細</strong>
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-3">
      <%= image_tag @item.get_image(200,200) %>
    </div>
  </div>
  <table class="col-5">
    <tbody>
      <tr>
        <td class="col-3">商品名</td>
        <td class="col-5"><%= @item.item_name %></td>
      </tr>
      <tr>
        <td class="col-3">商品説明</td>
        <td class="col-5"><%= @item.introduction %></td>
      </tr>
      <tr>
        <td class="col-3">税込み価格</td>
        <td class="col-5"><%= @item.with_tax_price%>円</td>
      </tr>
      <tr>
        <td class="col-3">税抜き価格</td>
        <td class="col-5"><%= @item.non_taxed_price %>円</td>
      </tr>
      <tr>
        <td></td>
        <td><%= link_to '編集する', edit_admin_item_path, class:"btn btn-success" %></td>
      </tr>
    </tbody>
  </table>
</div>