config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    get '/customers' => 'customers#index', as: 'customers'
    get '/customers/:id' => 'customers#show', as: 'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/:id' => 'customers#update', as: 'update'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :order_details
  end

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'edit_customer'
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/deleteprocess' => 'customers#deleteprocess', as: 'deleteprocess'
    patch '/customers/information' => 'customers#update', as: 'customer'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post '/orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get '/orders/completion' => 'orders#completion', as: 'completion'
    resources :orders
    resources :items
    resources :cart_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_show_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number, :email, :id, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<div class="container">
  <div class="col-4">
    <h4>
      <strong><%= @customer.last_name + @customer.first_name %>さんの会員情報編集</strong>
    </h4>
  </div>

<%= form_with model: @customer, url: admin_update_path do |f| %>

  <div class="row">
    <div class="col-3">
      <p>会員ID</p>
    </div>
    <div class="col-3">
      <p><%= @customer.id %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>氏名</p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :last_name %></p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :first_name %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>フリガナ</p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :last_name_kana %></p>
    </div>
    <div class="col-3">
      <p><%= f.text_field :first_name_kana %></p>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>郵便番号</p>
    </div>
    <div class="col-3">
      <%= f.text_field :postal_code %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>住所</p>
    </div>
    <div class="col-3">
      <%= f.text_field :address %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>電話番号</p>
    </div>
    <div class="col-3">
      <%= f.text_field :telephone_number %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>メールアドレス</p>
    </div>
    <div class="col-3">
      <%= f.email_field :email, autofocus: true, autocomplete: "email" %>
    </div>
  </div>

  <div class="row">
    <div class="col-3">
      <p>会員ステータス</p>
    </div>
    <div class="col-3">
      <span>
        <%= f.radio_button :is_active, :true %>
        <%= f.label :is_active_true, "有効" %>
      </span>
      <span>
        <%= f.radio_button :is_active, :false %>
        <%= f.label :is_active_false, "退会" %>
      </span>
    </div>
  </div>

  <div class="row">
    <div class="col-3"></div>
    <div class="col-3">
      <%= f.submit "変更を保存", class:"btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-3">
      <h4>
        <strong>会員一覧</strong>
      </h4>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="col-3">会員ID</th>
        <th class="col-3">氏名</th>
        <th class="col-3">メールアドレス</th>
        <th class="col-3">会員ステータス</th>
      </tr>
    </thead>
    <tbody>
<% @customers.each do |customer| %>
      <tr>
        <th class="row"><%= customer.id %></th>
        <td><%= link_to customer.last_name + customer.first_name, admin_customers_show_path(customer.id) %></td>
        <td><%= customer.email %></td>
        <td>
          <% if customer.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-muted">退会</p>
          <% end %>
        </td>
      </tr>
<% end %>
    </tbody>
  </table>
    <%= paginate @customers %>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-4">
      <h4>
        <strong><%= @customer.last_name + @customer.first_name %>さんの会員詳細</strong>
      </h4>
    </div>
  </div>
  <table class="table table-bordered">
    <tbody>
      <tr>
        <td class="table-secondary col-1">会員ID</td>
        <td class="col-4"><%= @customer.id %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">氏名</td>
        <td class="col-4"><%= @customer.last_name %> <%= @customer.first_name %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">フリガナ</td>
        <td class="col-4"><%= @customer.last_name_kana %> <%= @customer.first_name_kana %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">郵便番号</td>
        <td class="col-4"><%= @customer.postal_code %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">住所</td>
        <td class="col-4"><%= @customer.address %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">電話番号</td>
        <td class="col-4"><%= @customer.telephone_number %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">メールアドレス</td>
        <td class="col-4"><%= @customer.email %></td>
      </tr>
      <tr>
        <td class="table-secondary col-1">会員ステータス</td>
        <td class="col-4">
          <% if @customer.is_active == true %>
            <p class="text-success">有効</p>
          <% else %>
            <p class="text-muted">退会</p>
          <% end %>
        </td>
      </tr>
    </tbody>
  </table>
  <div class="row">
    <div class="col-3">
      <p><%= link_to '編集する', admin_customers_edit_path, class:"btn btn-success" %></p>
    </div>
  </div>
</div>