config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    get '/customers' => 'customers#index', as: 'customers'
    get '/customers/:id' => 'customers#show', as: 'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/:id' => 'customers#update', as: 'update'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :order_details
  end

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'edit_customer'
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/deleteprocess' => 'customers#deleteprocess', as: 'deleteprocess'
    patch '/customers/information' => 'customers#update', as: 'customer'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post '/orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get '/orders/completion' => 'orders#completion', as: 'completion'
    resources :orders
    resources :items
    resources :cart_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/order_details_controller.rb
class Admin::OrderDetailsController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @total_price = 0
  end

  private

  def order_detail_params
  params.require(:order_detail).permit(:order_id, :item_id, :ordering_price, :item_quantity)
  end
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/views/admin/order_details/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-5">
      <h4>
        <strong>注文履歴詳細</strong>
      </h4>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <p>
        <strong>購入者</strong>
      </p>
    </div>
    <div class="col-7">
      <%= link_to @order.customer.last_name + @order.customer.first_name, admin_customers_show_path %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <p>
        <strong>注文日</strong>
      </p>
    </div>
    <div class="col-7">
      <%= @order.created_at %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <p>
        <strong>配送先</strong>
      </p>
    </div>
    <div class="col-7">
      〒<%= @order.delivery_postal_code %> <%= @order.delivery_address %><br>
      <%= @order.delivery_name %>
    </div>
  </div>
  <div class="row">
    <div class="col-2">
      <p>
        <strong>支払い方法</strong>
      </p>
    </div>
    <div class="col-7">
      <%= @order.payment_method %>
    </div>
  </div>
  <table class="table">
    <thead>
      <tr>
        <th class="col-1">商品名</th>
        <th class="col-2">単価(税込)</th>
        <th class="col-2">数量</th>
        <th class="col-2">小計</th>
      </tr>
    </thead>
    <tbody>
    <% @order.order_details.each do |order_detail| %>
      <% @total_price= @total_price + order_detail.ordering_price %>
      <tr>
        <td class="col-2"><%= order_detail.item.item_name %></td>
        <td><%= order_detail.item.with_tax_price %></td>
        <td><%= order_detail.item_quantity %></td>
        <td><%= order_detail.ordering_price %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <table class="table table-bordered col-4">
    <tbody>
      <tr>
        <td class="col-2">送料</td>
        <td class="col-5">800</td>
      </tr>
      <tr>
        <td class="col-2">商品合計</td>
        <td class="col-5"><%= @total_price %></td>
      </tr>
      <tr>
        <td class="col-2">請求金額</td>
        <td class="col-1"><%= @total_price + 800 %></td>
      </tr>
    </tbody>
  </table>
</div>