config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  namespace :admin do
    root to: "homes#top"
    get '/customers' => 'customers#index', as: 'customers'
    get '/customers/:id' => 'customers#show', as: 'customers_show'
    get '/customers/:id/edit' => 'customers#edit', as: 'customers_edit'
    patch '/customers/:id' => 'customers#update', as: 'update'
    resources :items, only: [:index, :new, :create, :show, :edit, :update]
    resources :order_details
  end

  scope module: :public do
    root to: "homes#top"
    get '/about' => 'homes#about', as: 'about'
    get '/customers/my_page' => 'customers#show', as: 'my_page'
    get '/customers/information/edit' => 'customers#edit', as: 'edit_customer'
    get '/customers/withdrawal' => 'customers#withdrawal', as: 'withdrawal'
    patch '/customers/deleteprocess' => 'customers#deleteprocess', as: 'deleteprocess'
    patch '/customers/information' => 'customers#update', as: 'customer'
    delete '/cart_items/destroy_all' => 'cart_items#destroy_all', as: 'destroy_all'
    post '/orders/confirmation' => 'orders#confirmation', as: 'confirmation'
    get '/orders/completion' => 'orders#completion', as: 'completion'
    resources :orders
    resources :items
    resources :cart_items
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :item
  belongs_to :customer

  def subtotal
    item.with_tax_price * quantity
  end

  def sum_of_price
    item.with_tax_price * quantity
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  has_many :orders, dependent: :destroy

end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy

  def with_tax_price
    (non_taxed_price * 1.1).floor
  end

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum payment_method: { credit_card: 0, bank: 1 }
  has_many :order_details
  belongs_to :customer
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  def index
    @customers = Customer.page(params[:page])
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customers_show_path(@customer.id)
    else
      render :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number, :email, :id, :is_active)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
    @total_quantity = 0
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      render :new
    end
  end

  def index
    @items = Item.page(params[:page])
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private

  def item_params
    params.require(:item).permit(:image, :item_name, :introduction, :non_taxed_price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
end

app/controllers/admin/sessions_controller.rb
# frozen_string_literal: true

class Admin::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    def after_sign_in_path_for(resource)
      admin_root_path
    end

    def after_sign_out_path_for(resource)
      new_admin_session_path
    end
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana,
    :postal_code, :address, :telephone_number])
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_admin_header.html.erb
<% if admin_signed_in? %>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to '商品一覧', admin_items_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to '会員一覧', admin_customers_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to '注文履歴一覧', admin_root_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class:"btn btn-outline-dark" %>
    </li>
  </ul>
<% end %>

app/views/layouts/_customer_header.html.erb
<% if customer_signed_in? %>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to 'マイページ', my_page_path(current_customer), class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to '商品一覧', items_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to 'カート',  cart_items_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to 'ログアウト',  destroy_customer_session_path , method: :delete, class:"btn btn-outline-dark" %>
    </li>
  </ul>
<% elsif !admin_signed_in? %>
  <ul class="navbar-nav ml-auto">
    <li>
      <%= link_to 'About', about_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to '商品一覧', items_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to '新規登録', new_customer_registration_path, class:"btn btn-outline-dark mr-3" %>
    </li>
    <li>
      <%= link_to 'ログイン', new_customer_session_path, class:"btn btn-outline-dark" %>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-light border-bottom border-dark p-3">
        <div class="container">
          <a class="navbar-brand" href="/">NaganoCake</a>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <%= render 'layouts/admin_header' %>
            <%= render 'layouts/customer_header' %>
          </div>
        </div>
    </header>
    <main>
      <%= yield %>
    </main>
    <footer class="border-top border-dark">
    </footer>
  </body>
</html>